const dummyData = [
  {
    id: 0,
    image: require("./img/1.jpg"),
    rent: "2,095",
    restaurant: "Palm Harbor",
    location: "266 Green Valley, Highland Lake, FL",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Houses",
  },
  {
    id: 2,
    image: require("./img/2.jpg"),
    rent: "3000",
    restaurant: "Beverly Springfield",
    location: "2821 Lake Sevilla, Palm Harbour, TX",
    details: ["4 Beds", "2 Bathrooms", " 6x7.5m²"],
    propertyType: "Vila",
  },
  {
    id: 3,
    image: require("./img/3.jpg"),
    rent: "500",
    restaurant: "Samant Family Vila",
    location: "Dhonrh Asthan Road, Janta Bazar, TaJpur",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Houses",
  },
  {
    id: 4,
    image: require("./img/4.jpg"),
    rent: "3500",
    restaurant: "Sapphire Inn",
    location: "SKG Sugar Mill Road, Siwan",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Vila",
  },
  {
    id: 5,
    image: require("./img/5.jpg"),
    rent: "2,100",
    restaurant: "Le Gardenia",
    location: "Ranjan Path Rps More, Danapur",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Houses",
  },
  {
    id: 6,
    image: require("./img/6.jpg"),
    rent: "1,595",
    restaurant: "The Leela Palace",
    location: "23 Old Airport Road, Bengaluru",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Flat",
  },
  {
    id: 7,
    image: require("./img/7.jpg"),
    rent: "905",
    restaurant: "Tattva",
    location: "12Th Main Koramangala",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Flat",
  },
  {
    id: 8,
    image: require("./img/5.jpg"),
    rent: "1200",
    restaurant: "Embassy GolfLinks",
    location: "Embassy Golf Links Business Park, Domlur,",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "TownHouse",
  },
  {
    id: 9,
    image: require("./img/9.jpg"),
    rent: "1200",
    restaurant: "La Marvellar",
    location: "14th Cross Road South End Circle, Jaya Nagar",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "TownHouse",
  },
  {
    id: 10,
    image: require("./img/10.jpg"),
    rent: "1390",
    restaurant: "Roseate House",
    location: "GMR Hospitality District, New Delhi",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Vila",
  },
  {
    id: 11,
    image: require("./img/11.jpg"),
    rent: "2,200",
    restaurant: "Claridges",
    location: "The Claridges, 12, Dr. A.P.J., Aurangzeb Road",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Houses",
  },
  {
    id: 12,
    image: require("./img/12.jpg"),
    rent: "3300",
    restaurant: "Aventura",
    location: "1020 Fedora St, Los Angeles, CA",
    details: ["3 Beds", "2 Bathrooms", " 5x7m²"],
    propertyType: "Flat",
  },
];
export default dummyData;
